seed: 42
device: cuda

data:
  data_dir: /mnt/c/Users/lhe09/projects/msd_brain
  roi_size: [128,128,128]

training:
  batch_size: 2
  lr: 0.0005
  epochs: 500
  patience: 20

model:
  name: dynunet
  in_channels: 4
  out_channels: 4

paths:
  output_dir: outputs